name: Setup Test Database
description: Set up the test Database

runs:
  using: "composite"
  steps:
    - name: Setup PSQL
      shell: bash
      run: |
        cp config/database.yml.sample config/database.yml
        RAILS_ENV=test bundle exec rails db:setup


