name: Set up db and storage config
description: Set up db and storage configurations.

runs:
  using: "composite"
  steps:
    - name: Set up db and storage configuration
      shell: bash
      run: |
        cp config/database.yml.sample config/database.yml
        cp config/storage.yml.sample config/storage.yml
        RAILS_ENV=test bundle exec rails db:setup


