name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests

    services:
      postgres:
        image: postgres:15.0-alpine

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        ports:
          - 5432:5432

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Test Database
        run: bundle exec rails db:setup
        env:
          RAILS_ENV: test

      - name: Prepare for testing
        run: bundle exec rails test:prepare
        env:
          RAILS_ENV: test

      - name: Run tests
        run: bundle exec rails test
